import { create } from 'zustand'
import { persist } from 'zustand/middleware'
import type { Member, ActivityEvent, ActivityState, MemberWithState, AISuggestion, AISuggestionType } from '../types'
import { SEED_MEMBERS, SEED_ACTIVITIES } from '../data/fofData'

// ─── Activity State Classification Rules ─────────────────────────────────────
// Newly Joined  : joined ≤ 14 days ago (regardless of activity)
// Highly Active : ≥ 4 activity events in last 30 days
// Active        : ≥ 1 event in last 30 days AND joined > 14 days ago
// At Risk       : last activity 31-60 days ago
// Dormant       : last activity > 60 days ago OR never active and joined > 14 days ago

const DAY_MS = 86_400_000

function computeState(
  member: Member,
  activities: ActivityEvent[]
): { state: ActivityState; count30d: number; lastActivityDate?: string } {
  const now = Date.now()
  const joinedMs = new Date(member.joinDate).getTime()
  const daysSinceJoin = (now - joinedMs) / DAY_MS

  const memberActs = activities.filter((a) => a.memberId === member.id)
  const sorted = [...memberActs].sort(
    (a, b) => new Date(b.date).getTime() - new Date(a.date).getTime()
  )

  const lastActivity = sorted[0]
  const lastActivityDate = lastActivity?.date

  const thirtyDaysAgo = now - 30 * DAY_MS
  const count30d = memberActs.filter(
    (a) => new Date(a.date).getTime() >= thirtyDaysAgo
  ).length

  // Newly Joined takes precedence (regardless of any other activity)
  if (daysSinceJoin <= 14) {
    return { state: 'Newly Joined', count30d, lastActivityDate }
  }

  if (count30d >= 4) return { state: 'Highly Active', count30d, lastActivityDate }
  if (count30d >= 1) return { state: 'Active', count30d, lastActivityDate }

  if (!lastActivity) return { state: 'Dormant', count30d, lastActivityDate }

  const daysSinceLast = (now - new Date(lastActivity.date).getTime()) / DAY_MS
  if (daysSinceLast > 60) return { state: 'Dormant', count30d, lastActivityDate }
  if (daysSinceLast > 30) return { state: 'At Risk', count30d, lastActivityDate }

  return { state: 'Active', count30d, lastActivityDate }
}

// ─── AI Suggestion Engine (Simulated) ────────────────────────────────────────
function generateAISuggestion(
  member: MemberWithState,
  allMembers: MemberWithState[],
  type: AISuggestionType
): AISuggestion {
  const disclaimer =
    '[SIMULATED] This suggestion is generated by a rule-based system, not a live AI model. No message has been sent. All outputs require human review before any action is taken.'

  if (type === 'activity_summary') {
    const recent = member.recentActivities.slice(0, 3)
    const summary = recent.length
      ? recent
          .map((a) => `• ${a.type} in ${a.space} (${a.date})`)
          .join('\n')
      : 'No recent activity recorded in the last 30 days.'
    return {
      type,
      label: 'Activity Summary',
      content: `Recent activity for ${member.name} (last 30 days):\n\n${summary}\n\nState: ${member.activityState} | Events: ${member.activityCount30d} in 30 days.`,
      disclaimer,
    }
  }

  if (type === 'space_suggestion') {
    const spaceMap: Record<string, string[]> = {
      'Algorithmic Trading': ['#tools-and-tech', '#market-commentary'],
      'ESG Investing': ['#market-commentary', '#resources-library'],
      'CFA Prep': ['#study-groups', '#resources-library'],
      Mentoring: ['#peer-intros', '#alumni-network'],
      Fintech: ['#tools-and-tech', '#general-chat'],
      'Machine Learning': ['#tools-and-tech'],
      Derivatives: ['#study-groups', '#market-commentary'],
      'Impact Investing': ['#resources-library', '#events-calendar'],
      'Private Equity': ['#peer-intros', '#alumni-network'],
    }
    const suggested =
      member.interests
        .flatMap((i) => spaceMap[i] ?? [])
        .filter((s, idx, arr) => arr.indexOf(s) === idx)
        .slice(0, 2) || [member.primarySpace]

    return {
      type,
      label: 'Community Space Suggestion',
      content: `Based on ${member.name}'s interests (${member.interests.slice(0, 3).join(', ')}), the following spaces may be a great fit:\n\n${suggested.map((s) => `• ${s}`).join('\n')}\n\nConsider sharing a relevant recent discussion or resource from these channels.`,
      disclaimer,
    }
  }

  if (type === 'peer_intro') {
    const peers = allMembers
      .filter(
        (m) =>
          m.id !== member.id &&
          (m.primarySpace === member.primarySpace ||
            m.interests.some((i) => member.interests.includes(i))) &&
          m.activityState !== 'Dormant'
      )
      .slice(0, 2)

    const introLines = peers.length
      ? peers
          .map(
            (p) =>
              `• ${p.name} (${p.role}) — shares interest in ${p.interests.find((i) => member.interests.includes(i)) ?? p.primarySpace}`
          )
          .join('\n')
      : 'No matching peers found at this time.'

    return {
      type,
      label: 'Peer Introduction Suggestion',
      content: `${member.name} may benefit from connecting with:\n\n${introLines}\n\nReview these suggestions and make the introduction personally if appropriate.`,
      disclaimer,
    }
  }

  if (type === 'activation_message') {
    const daysSince = member.lastActivityDate
      ? Math.round(
          (Date.now() - new Date(member.lastActivityDate).getTime()) / DAY_MS
        )
      : null

    const msg = `Hi ${member.name.split(' ')[0]},\n\nWe've been thinking of you! It's been a while since we've seen you in the community and we'd love to reconnect.\n\nWe have some great discussions happening in ${member.primarySpace} that align with your interest in ${member.interests[0] ?? 'finance'}, and there are members who'd love to hear your perspective.\n\nWould you be up for a quick catch-up call this week?\n\n— [Community Manager Name]`
    return {
      type,
      label: 'Draft Activation Message',
      content: `Suggested re-engagement message${daysSince ? ` (${daysSince} days since last activity)` : ''}:\n\n${msg}`,
      disclaimer,
    }
  }

  // next_step
  const steps: Record<ActivityState, string> = {
    'Newly Joined': `Schedule a welcome call with ${member.name} within the next 3 days. Share the onboarding checklist and invite them to introduce themselves in #introductions.`,
    Active: `Recognise ${member.name}'s recent contribution in ${member.primarySpace}. Consider inviting them to an upcoming event or suggesting a peer introduction.`,
    'Highly Active': `${member.name} is a power contributor! Consider featuring them in the community spotlight, inviting them to co-host an event, or becoming a formal mentor.`,
    'At Risk': `${member.name} has not been active for 31-60 days. Send a warm personal check-in message. Do not use commercial messaging. Reference their last known interest: ${member.interests[0] ?? 'the community'}.`,
    Dormant: `${member.name} has been dormant. A personal LinkedIn message or email re-engagement is recommended. Keep it genuinely warm — no sales language.`,
  }

  return {
    type,
    label: 'Recommended Next Step',
    content: steps[member.activityState],
    disclaimer,
  }
}

// ─── Store ────────────────────────────────────────────────────────────────────
interface MemberStoreState {
  members: Member[]
  activities: ActivityEvent[]
  isLoading: boolean

  // Computed
  getMembersWithState: () => MemberWithState[]
  getMemberWithState: (id: string) => MemberWithState | undefined

  // CRUD
  addMember: (m: Omit<Member, 'id'>) => void
  updateMember: (id: string, updates: Partial<Member>) => void

  // Activity
  addActivity: (a: Omit<ActivityEvent, 'id'>) => void

  // AI
  getAISuggestion: (memberId: string, type: AISuggestionType) => AISuggestion | null
}

export const useMemberStore = create<MemberStoreState>()(
  persist(
    (set, get) => ({
      members: SEED_MEMBERS,
      activities: SEED_ACTIVITIES,
      isLoading: false,

      getMembersWithState: () => {
        const { members, activities } = get()
        return members.map((m) => {
          const { state, count30d, lastActivityDate } = computeState(m, activities)
          const thirtyDaysAgo = Date.now() - 30 * DAY_MS
          const memberActs = activities
            .filter((a) => a.memberId === m.id)
            .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime())
          const recentActivities = memberActs.filter(
            (a) => new Date(a.date).getTime() >= thirtyDaysAgo
          )
          return {
            ...m,
            activityState: state,
            activityCount30d: count30d,
            lastActivityDate,
            recentActivities,
            allActivities: memberActs,
          }
        })
      },

      getMemberWithState: (id) => {
        return get().getMembersWithState().find((m) => m.id === id)
      },

      addMember: (memberData) => {
        const newMember: Member = {
          ...memberData,
          id: `mem-${Date.now()}`,
        }
        set((s) => ({ members: [newMember, ...s.members] }))
      },

      updateMember: (id, updates) => {
        set((s) => ({
          members: s.members.map((m) => (m.id === id ? { ...m, ...updates } : m)),
        }))
      },

      addActivity: (actData) => {
        const newAct: ActivityEvent = {
          ...actData,
          id: `act-${Date.now()}`,
        }
        set((s) => ({ activities: [newAct, ...s.activities] }))
      },

      getAISuggestion: (memberId, type) => {
        const members = get().getMembersWithState()
        const member = members.find((m) => m.id === memberId)
        if (!member) return null
        return generateAISuggestion(member, members, type)
      },
    }),
    {
      name: 'fof-crm-store',
      partialize: (state) => ({
        members: state.members,
        activities: state.activities,
      }),
    }
  )
)
